### ISSUE TITLE
Automatically detect namespace from Kubeconfig

### ISSUE THREAD

**Issue by Pscheidl** [h2oai/h2o-kubernetes#7]
Kubeconfig might contain namespace name - `h2ok` should replace the default value with the value from the kubeconfig, unless user specifies the namespace specifically.

Example OpenShift Kubeconfig

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://api.us-east-1.starter.openshift-online.com:6443
  name: api-us-east-1-starter-openshift-online-com:6443
contexts:
- context:
    cluster: api-us-east-1-starter-openshift-online-com:6443
    namespace: pavel-test
    user: <omitted>
  name: pavel-test/api-us-east-1-starter-openshift-online-com:6443/<omitted>
current-context: <omitted>t/api-us-east-1-starter-openshift-online-com:6443/<omitted>
kind: Config
preferences: {}
users:
- name: <omitted>
  user:
    token: <omitted>
```
